config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'specs/editSpecs'

  root 'car#index'
  get 'car/newCar' => 'car#newCar' , as: 'new_car'
  get '/' => 'car#index', as: 'all_cars'
  post '/car/newCar' => 'car#create'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :models
end

app/models/line.rb
class Line < ActiveRecord::Base
	belongs_to :model
end

app/models/model.rb
class Model < ActiveRecord::Base
	
	mount_uploader :image, ImageUploader
	belongs_to :brand
	has_many :lines
end

app/models/spec.rb
class Spec < ActiveRecord::Base
	belongs_to :line
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   #add messaging service between users
   acts_as_messageable :required   => :body

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/car_controller.rb
class CarController < ApplicationController
  
  def newCar

  end

  def index

  end

  def create

  	# @current_brand = Brand.find_by(name: params[:createCar][:brand])
	@current_brand = Brand.where("name ILIKE ?", params[:createCar][:brand]).first

  	if @current_brand == nil
  			b = Brand.create(name: params[:createCar][:brand].upcase)
  			bm = Model.create(name: params[:createCar][:model].upcase, model_year: params[:createCar][:year], brand: b)
  			bml = Line.create(name: params[:createCar][:line].capitalize, price: params[:createCar][:price], model: bm)
  	else
  		@current_model = Model.where("name ILIKE ? and model_year = ?", params[:createCar][:model], params[:createCar][:year]).first
  		if @current_model == nil
  				m = Model.create(name: params[:createCar][:model].upcase, model_year: params[:createCar][:year], brand: @current_brand)
  				Line.create(name: params[:createCar][:line].capitalize, price: params[:createCar][:price], model: m)
		else
			# @current_line = Line.where("name ILIKE ?", params[:createCar][:line]).first
			# current_line = @current_brand.@current_model.find_by(name: params[:createCar][:line])
			# if @current_line == nil
					Line.create(name: params[:createCar][:line].capitalize, price: params[:createCar][:price], model: @current_model)
			# end

		end
	end

	redirect_to all_cars_path

  end

  def update
  	
  end

end

app/controllers/specs_controller.rb
class SpecsController < ApplicationController

	before_action :authenticate_user!
	
  def editSpecs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/specs_helper.rb
module SpecsHelper
end

app/views/car/addSpecs.html.erb
<%= form_for (:specs, :url => {:method => 'make'}) do |s| %>

<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :transmission, :placeholder => 'Engine' %>
<%= s.text_field :shifts, :placeholder => 'Engine' %>
<%= s.text_field :type, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>
<%= s.text_field :engine, :placeholder => 'Engine' %>

app/views/car/index.html.erb
<h1>Car#index</h1>
<h3>Index All Cars</h3>

<div>
<table class = "table-fill">

		<tr>
			<td>Model</td>
			<td>Year</td>
			<td>Line</td>
			<td>Price</td>
			<td>View Specs</td>
		</tr>
		<!-- <table> -->
			<% Brand.all.each do |b| %>
			<th><%= b.name %></th>
			<tr>
				<% b.models.all.each do |bm| %>
				<tr rawspan= <%= b.models.size.to_s %> >
					<td><%= bm.name %></td>
					<td><%= bm.model_year %></td>
					<% bm.lines.all.each do |bml| %>
					<tr rawspan= <%= bm.lines.size.to_s %>>
						<td><%= link_to bml.name, '#' %></td>
						<% if bml.price == nil %>
						<td> 0 </td>
						<% else %>
						<td><%= bml.price %></td>
						<% end %>
						<!-- <td><%= link_to 'View Specifications', '#' %></td> -->
					</tr>
					<% end %>
				</tr>
				<% end %>
			</tr>
			<% end %>

		<!-- </table> -->


	</table>

	<%= link_to 'Create Car', new_car_path %>

</div>

app/views/car/newCar.html.erb
<h1>Car#newCar</h1>
<h3>Create New Car</h3>

<%= form_for :createCar do |c| %>

<%= c.label 'Brand' %>
<%= c.text_field :brand %>

<%= c.label 'Model' %>
<%= c.text_field :model %>

<%= c.label 'Year' %>
<%= c.text_field :year %>

<%= c.label 'Line' %>
<%= c.text_field :line %>

<%= c.label 'Price' %>
<%= c.text_field :price %>
<br>
<br>

<%= c.label 'Specs' %>
<!-- <%= c.text_field :brand %> -->

<%= c.submit 'Create Car' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cars</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/specs/editSpecs.html.erb
<h1>Specs#editSpecs</h1>
<p>Find me in app/views/specs/editSpecs.html.erb</p>